### ISSUE TITLE
Game crashes when loading Exhibition match

### ISSUE THREAD

**Issue by franchiceddhu** [Davek84/MatchOdds#2]
As the title says. When I enable this mod, the game crashes when loading bots (I've tested in 1v1 Soccar match, All-Star difficulty). I am able to reproduce this issue every time.

Since I'm here, I'm also leaving a suggestion: make the odds display appears only with Scoreboard or during replays.

**Comment by Davek84** [comment]
This should be fixed in the latest version + as a bonus I've added in the ability for the odds to only display on the Scoreboard.
Not approved yet on the BakkesMod Plugin website, but you can grab the latest file from here - https://github.com/Davek84/MatchOdds/releases/tag/1.7 

**How to install:**
- Copy the matchodds.set file over the current one in your 'bakkesmod/plugins/settings' folder
- Copy the matchodds.dll file over the current one in your 'bakkesmod/plugsin' folder
